"""Update created_at Product model

Revision ID: 0b53295458a5
Revises: 8c172a94a970
Create Date: 2023-06-06 18:52:18.923140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b53295458a5'
down_revision = '8c172a94a970'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
