"""Initial migrations

Revision ID: 9239de02a775
Revises: 59d47097c44b
Create Date: 2023-06-06 16:21:49.659081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9239de02a775'
down_revision = '59d47097c44b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
